### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve './Partials/Styles' in '***/node_modules/react-advance-jalaali-datepicker/dist'

### ISSUE THREAD

**Issue by mehranhatami** [A-Kasaaian/react-advance-jalaali-datepicker#5]
Hello,
Using this library I have encountered an issue when webpack is trying to bundle the module:

```shell
[21:08:17] Starting 'bundle'...
ModuleNotFoundError: Module not found: Error: Can't resolve './Partials/Styles' in '***/node_modules/react-advance-jalaali-datepicker/dist'
    at factoryCallback (***/node_modules/webpack/lib/Compilation.js:269:40)
    at factory (***/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (***/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (***/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at ***/node_modules/webpack/node_modules/async/dist/async.js:3861:9
    at ***/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (***/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at ***/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at ***/node_modules/webpack/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (***/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
```
Node version: v8.11.1
NPM version: 5.8.0
React version: ^16.2.0
Webpack version: ^4.2.0

I'd be really appreciated if you help me resolve the issue.

**Comment by A-Kasaaian** [comment]
@mehranhatami  May I have your webpack config and also part f code you have imported the time picker

**Comment by A-Kasaaian** [comment]
It was an Issue with file name in dist folder, which is fixed in the last release.
